apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udagram-api-reverseproxy
  name: udagram-api-reverseproxy
spec:
  replicas: 1
selector:
  matchLabels:
    app: udagram-api-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-api-reverseproxy
    spec:
      containers:
        - image: dhadhazi/udagram-api-reverseproxy
          name: udagram-api-reverseproxy
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
