apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: udagram-api-reverseproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
        - image: dhadhazi/udagram-api-reverseproxy
          name: udagram-api-reverseproxy
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
